set(slm_FILES
    "./src/Clipping.h"
    "./src/Clipping.cpp"
    "./src/LineT.h"
    "./src/PostscriptInterpreter.h"
    "./src/Scene.h"
    "./src/slm.h"
    "./src/slm.cpp"
    "./src/slmPCH.h"
    "./src/VecT.h"
    "./src/Viewport.h"
    "./src/Viewport.cpp"
)