set(slm_FILES
    "./src/PBMImage.cpp"
    "./src/PBMImage.h"
    "./src/PostscriptInterpreter.cpp"
    "./src/PostscriptInterpreter.h"
    "./src/Primitive.cpp"
    "./src/Primitive.h"
    "./src/Scene.cpp"
    "./src/Scene.h"
    "./src/slm.h"
    "./src/slmPCH.h"
    "./src/Vec.cpp"
    "./src/Vec.h"
)