set(slm_test_FILES
    "./src/ClippingUnitTests.cpp"
    "./src/LineTUnitTests.cpp"
    "./src/PBMImageUnitTests.cpp"
    "./src/PolygonTUnitTests.cpp"
    "./src/PostscriptInterpreter.cpp"
    "./src/VecTUnitTests.cpp"
    "./src/ViewportUnitTests.cpp"
)