set(slm_test_FILES
    "./src/HelperFunctions.cpp"
    "./src/HelperFunctions.h"
    "./src/MatUnitTests.cpp"
    "./src/PBMImageUnitTests.cpp"
    "./src/PostscriptInterpreterUnitTests.cpp"
    "./src/PPMImageUnitTests.cpp"
    "./src/PrimitiveUnitTests.cpp"
    "./src/SceneUnitTests.cpp"
    "./src/SMFInterpreterUnitTests.cpp"
    "./src/VecUnitTests.cpp"
)